// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmgymaqzkwtghbqszfjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZ3ltYXF6a3d0Z2hicXN6ZmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTE1NjUsImV4cCI6MjA2MTg2NzU2NX0.BwszDQbxV0s6ym1NUnHdtJYac4Fbzvabco9WQY9g1Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);